sudo: required

language: cpp

cache:
  directories:
    - /opt/devkitpro/pacman/var/cache/pacman/pkg/

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  - echo -e "\n\nmachine github.com\n  login $GITHUB_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman -S switch-{dev,curl,portlibs,glfw,mesa,glm} libnx --noconfirm
  - source /etc/profile.d/devkit-env.sh

script:
  - make -j8

before_deploy:
    - git config --local user.name "WerWolv"
    - git config --local user.email "werwolv98@gmail.com"
    - export TRAVIS_TAG=snapshot
    - git tag -d $TRAVIS_TAG
    - git tag $TRAVIS_TAG
  
deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  file: application/out/EdiZon.nro
  skip_cleanup: true
  overwrite: true
  name: "Snapshot Build"
  body: "This snapshot was compiled on the $(date +'%d. %B %Y') from commit [$(printf %.7s $(git rev-parse HEAD))](https://github.com/WerWolv/EdiZon-Rewrite/commit/$(git rev-parse HEAD)). </br> </br> It may be unstable, use it at your own risk. </br> To install it, place the EdiZon.nro in your /switch/EdiZon folder replacing the file in there."
  on:
    branch: master